class Channel {

  public static DB_CONNECTIONS_WERE_UPDATED = 'DB_CONNECTIONS_WERE_UPDATED';
  public static BOT_COMMANDS_WERE_UPDATED = 'BOT_COMMANDS_WERE_UPDATED';


  public static NOTIFICATIONS_API_WERE_UPDATED = 'NOTIFICATIONS_API_WERE_UPDATED';

  public static OPEN_BOT_ACCESS_LIST_DIALOG = 'OPEN_BOT_ACCESS_LIST_DIALOG';

}

export default Channel;
