org.springframework.security.level: INFO
spring:
  h2:
    console:
      enabled: true
server:
  port: 9876

security:
  authentication:
    jwt:
      secret: d6dd67ebbb7bd7dc24e00fd3552495233a84605c
      tokenValidityInSeconds: 86400 # Token is valid 24 hours
      tokenValidityInSecondsForRememberMe: 2500000 # Token is valid 29 days
logging:
  file:
    name: ${user.home}/.support-terminal/application.log