class Channel{
    public static BOT_COMMANDS_WERE_UPDATED = 'BOT_COMMANDS_WERE_UPDATED';
    public static OPEN_ADD_BOT_COMMAND_DIALOG = 'OPEN_ADD_BOT_COMMAND_DIALOG';
    public static OPEN_EDIT_BOT_COMMAND_DIALOG = 'OPEN_EDIT_BOT_COMMAND_DIALOG';
    public static DB_CONNECTIONS_WERE_UPDATED = 'DB_CONNECTIONS_WERE_UPDATED';
    public static NOTIFICATIONS_API_WERE_UPDATED = 'BOTS_WERE_UPDATED';

}

export default Channel;
