class Channel{
  public static OPEN_ADD_DB_CONNECTION_DIALOG = "OPEN_ADD_DB_CONNECTION_DIALOG";
  public static OPEN_EDIT_DB_CONNECTION_DIALOG = "OPEN_EDIT_DB_CONNECTION_DIALOG";
  public static DB_CONNECTIONS_WERE_UPDATED = "DB_CONNECTIONS_WERE_UPDATED";

  public static OPEN_ADD_WEB_USER_DIALOG = "OPEN_ADD_WEB_USER_DIALOG";
  public static OPEN_EDIT_WEB_USER_DIALOG = "OPEN_EDIT_WEB_USER_DIALOG";
  public static WEB_USERS_WERE_UPDATED = "WEB_USERS_WERE_UPDATED";

  public static OPEN_ADD_TEXT_HANDLER_PROCESSOR_DIALOG = "OPEN_ADD_TEXT_HANDLER_PROCESSOR_DIALOG";
  public static OPEN_EDIT_TEXT_HANDLER_PROCESSOR_DIALOG = "OPEN_EDIT_TEXT_HANDLER_PROCESSOR_DIALOG";
  public static TEXT_HANDLER_PROCESSORS_WERE_UPDATED = "TEXT_HANDLER_PROCESSORS_WERE_UPDATED";



  public static BOTS_WERE_UPDATED = "BOTS_WERE_UPDATED";
  public static OPEN_ADD_BOT_DIALOG = "OPEN_ADD_BOT_DIALOG";
  public static OPEN_EDIT_BOT_DIALOG = "OPEN_EDIT_BOT_DIALOG";
  public static OPEN_BOT_ACCESS_LIST_DIALOG = "OPEN_BOT_ACCESS_LIST_DIALOG";

}

export default Channel;
