class Channel{
    public static BOT_TASKS_WERE_UPDATED = "BOT_TASKS_WERE_UPDATED";
    public static OPEN_ADD_BOT_TASK_DIALOG = "OPEN_ADD_BOT_TASK_DIALOG";
    public static OPEN_EDIT_BOT_TASKS_DIALOG = "OPEN_EDIT_BOT_TASKS_DIALOG";
    public static DB_CONNECTIONS_WERE_UPDATED = "DB_CONNECTIONS_WERE_UPDATED";
    public static BOTS_WERE_UPDATED = "BOTS_WERE_UPDATED";

}

export default Channel;
